### ISSUE TITLE
add topic

### ISSUE THREAD

**Issue by Beliavsky** [degawa/par-funnel#1]
I suggest adding topics such as `unit-testing`, `unit-test`, `test-runner`, `namelist`, `fortran` to the About section at https://github.com/degawa/par-funnel

**Comment by degawa** [comment]
Thank you for your suggestion.
I always need to remember to add topics to the About section.
I added some topics, including `unit-testing`, `unit-test`, `test-runner`, `namelist`, `fortran`, and others.
